[project]
name = "stegohelix"
version = "0.1.0"
description = "Advanced Image Steganography with Military-Grade Encryption"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argon2-cffi",
    "numpy",
    "opencv-python-headless",
    "pycryptodome",
    "streamlit",
]
